name: Python Tests

on:
  push:
    branches:
      - main  # Bu faqat `main` branchga push qilganda ishga tushadi
  pull_request:
    branches:
      - main  # Pull request yaratganda ham ishga tushadi

jobs:
  test:
    runs-on: ubuntu-latest  # Ishga tushirish uchun eng so'nggi Ubuntu versiyasini tanlaymiz

    steps:
      - name: Check out the code
        uses: actions/checkout@v2  # Kodingizni repository'dan klonlash

      - name: Set up Python
        uses: actions/setup-python@v2  # Python versiyasini o'rnatish
        with:
          python-version: '3.9'  # Istalgan Python versiyasini tanlang

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Testlar va boshqa kutubxonalarni o'rnatish

      - name: Run tests
        run: |
          pytest tests/  # Testlarni ishlatish
